Repository RAF-SI-2024/Banka-1-Frontend, pull requests merged in 2025-03, with the labels that each got.

#131 Added OWNERS file
  OWNERS
Labels: size/S

#132 Zavrsen task #124 (Upravljanje kreditima od strane zaposlenog i admina)
  src/pages/portals/AllLoansEmployeePortal.jsx
Labels: lgtm, approved

#130 zavrsen ceo task(hvala milice)
  src/components/common/ApproveLoanButton.jsx
  src/components/common/DenyLoanButton.jsx
  src/pages/portals/PendingLoansEmployeePortal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#128 Popravljen RecieversPortal od prosle nedelje. Radi ucitavanje svih primalaca odredjenog racuna , dodavanje novog primalaca, azuriranje postojecih i brisanje primalaca.
  src/App.js
  src/components/common/RecipientModal.jsx
  src/pages/portals/ReceiversPortal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#133 Modal za kreiranje zahteva za novi kredit
  src/components/common/LoanRequestModal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#134 Promenjen payment code(dohvata se sa back-a), popravljeno slanje tran…
  src/components/common/PaymentResultModal.jsx
  src/pages/portals/NewPaymentPortal.jsx
  src/services/AxiosBanking.js
  src/styles/NewPaymentPortal.css
Labels: size/L, lgtm, approved

#135 loan stranica sa pop up-om o detaljima jednog kredita
  src/App.js
  src/components/common/LoanDetailsModal.jsx
  src/components/mainComponents/Sidebar.jsx
  src/pages/portals/LoansPortal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#136 [bug-fix] poprevka gresaka na LoansPortal
  src/components/common/LoanDetailsModal.jsx
  src/pages/portals/LoansPortal.jsx
  src/services/AxiosBanking.js
Labels: lgtm, approved, size/XL

#137 Zavrsena Menjacnica
  src/App.js
  src/components/mainComponents/Sidebar.jsx
  src/pages/exchange/CheckEquivalency.jsx
  src/pages/exchange/ExchangeRateList.jsx
  src/pages/portals/LoansPortal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#138 radi.(prvo upisati recipient acccount pa onda reccipient name)
  src/pages/portals/NewPaymentPortal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#139 Made API urls configurable
  .env
  src/components/transactionComponents/FastPayments.jsx
  src/services/AxiosBanking.js
  src/services/AxiosUser.js
  src/services/TansactionService.js
  src/services/transactionService.js
Labels: size/L, lgtm, approved

#146 Dodat novi AxiosTrading za traiding server
  .env
  src/services/AxiosTrading.js
Labels: lgtm, size/S, approved

#148 promene u testiranju br 1
  src/components/common/NewCurrentAccountModal.jsx
  src/pages/common/HomePage.jsx
  src/pages/portals/CustomerPortal.jsx
  src/pages/portals/EmployeePortal.jsx
Labels: size/L, lgtm, approved

#149 naknadno cu dodati rutu za orders kod supervizora
  src/App.js
  src/components/mainComponents/Sidebar.jsx
  src/context/AuthGuard.jsx
Labels: size/L, lgtm, approved

#151 dodate sve rute za side bar
  src/App.js
  src/components/mainComponents/Sidebar.jsx
Labels: lgtm, size/S, approved

#152 popravljen fast payments da je uvezan sa ccountom ne sa userom
  src/components/transactionComponents/FastPayments.jsx
  src/services/AxiosBanking.js
Labels: lgtm, size/S, approved

#159 Ne znam
  src/components/common/ResetUsedLimitButton.jsx
  src/pages/portals/ActuarialManagementPortal.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#158 buy popup za kreiranje ordera
  src/components/createOrderComponents/BuyModal.jsx
Labels: size/L, lgtm, approved

#150 Add docker build for frontend
  .dockerignore
  .prow/build.yml
  Caddyfile
  Dockerfile
  compose.yaml
  nginx.conf.template
Labels: size/L, lgtm, approved

#160 Made CD jobs overwrite API URLs
  .prow/build.yml
Labels: lgtm, approved, size/XS

#162 Update README.md
  README.md
Labels: lgtm, size/S, approved

#163 dodato dodavanje departmenta za nove uloge
  src/App.js
  src/pages/portals/EmployeePortal.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#164 dosta stvari popravljeno, poslednje je toggle za block and deactivate…
  src/pages/portals/EmployeeBankAccountsPortal.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/pages/portals/EmployeePortal.jsx
  src/services/AxiosBanking.js
Labels: lgtm, approved

#165 popravljeno blocked dugme
  src/pages/portals/EmployeeCardsPortal.jsx
Labels: lgtm, approved

#167 Popravljene Transkacije, filter po racunu vremenu statusu i kolicini novca
  src/components/transactionTable/TransactionDetailsModal.jsx
  src/pages/transactions/TransactionsPage.jsx
Labels: lgtm, approved

#170 Update README.md
  README.md
Labels: lgtm, approved

#166 added balance to creating new customer with new account
  src/components/common/NewCurrentAccountModal.jsx
Labels: lgtm, approved, size/XS

#168 Popravljene rute kod detalja i srednjen izgled tabele u accountsportal
  src/components/common/AccountDetailsModal.jsx
  src/components/common/LoanDetailsModal.jsx
  src/pages/portals/AccountsPortal.jsx
Labels: lgtm, size/M, approved

#169 ispravljen modal za novi kredit po spec i azurirana submitLoanRequest …
  src/components/common/LoanRequestModal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#171 radi loan details
  src/App.js
  src/components/common/LoanDetailsModal.jsx
  src/components/mainComponents/Sidebar.jsx
  src/context/AuthGuard.jsx
  src/pages/portals/LoansPortal.jsx
Labels: size/L, lgtm, approved

#172 Popravljene rute za kartice PATCH
  src/components/common/CardDetailsModal.jsx
  src/components/common/ChangeCardLimitModal.jsx
  src/components/common/ChangeCardNameModal.jsx
  src/components/common/CreateCardModal.jsx
  src/components/lists/AccountTransactionLists.jsx
  src/services/AxiosBanking.js
Labels: lgtm, approved

#173 izmenjena logika za auth guard, app js i side bar
  src/App.js
  src/components/mainComponents/Sidebar.jsx
  src/context/AuthGuard.jsx
Labels: lgtm, approved

#180 Tranksakcije popravljene ne radi internal za testiranje ali radi
  src/components/transactionTable/TransactionDetailsModal.jsx
  src/pages/transactions/TransactionsPage.jsx
Labels: size/L, lgtm, approved

#182 Popravljeno za fast payment, OTP baca 500 bez razloga? tj dodata je l…
  src/pages/portals/NewPaymentPortal.jsx
Labels: size/L, lgtm, approved

#183 izmenjen buy popup
  src/components/createOrderComponents/BuyModal.jsx
Labels: lgtm, size/M, approved

#181 Dva portala za kupovinu hartija su usaglaseni sa beckom, popravljen j…
  src/components/securititesBuyingComponents/SecuritiesTable.jsx
  src/pages/portals/securitiesBuyingPortal/ActuarySecuritiesBuyingPortal.jsx
  src/pages/portals/securitiesBuyingPortal/ClientSecuritiesBuyingPortal.jsx
Labels: size/L, lgtm, approved

#185 Prepravke
  src/App.js
  src/components/securititesBuyingComponents/SecuritiesTable.jsx
  src/pages/portals/ReceiversPortal.jsx
Labels: size/L, lgtm, approved

#186 izmene na buy modalu
  src/components/createOrderComponents/BuyModal.jsx
Labels: lgtm, size/S, approved

#187 cypress
  package-lock.json
  package.json
Labels: lgtm, approved

#188 u opisu su popravljeni bagovi za klijenta
  src/pages/portals/AccountsPortal.jsx
  src/pages/portals/EmployeeBankAccountsPortal.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/services/AxiosBanking.js
Labels: lgtm, size/M, approved

#189 Fix backend database issue in compose
  OWNERS
  compose.yaml
Labels: lgtm, size/S, approved

#190 Initial Cypress setup and initial e2e/commands
  cypress.config.js
  cypress/e2e/admin/add_employee.cy.js
  cypress/e2e/admin/block_employee.cy.js
  cypress/e2e/admin/edit_customer.cy.js
  cypress/e2e/admin/login_logout.cy.js
  cypress/e2e/hello_world.cy.js
  cypress/support/admin/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  webpack.config.js
Labels: lgtm, approved

#192 Fix
  cypress/support/admin/commands.js
Labels: lgtm, approved, size/XS

#193 Headless Fix
  .gitignore
  cypress.config.js
  cypress/e2e/admin/deny_loan.cy.js
  cypress/e2e/hello_world.cy.js
  cypress/support/admin/commands.js
Labels: lgtm, approved

#195 Hasky and E2e tests
  .husky/pre-commit
  cypress/e2e/customer/account/apply_loan.cy.js
  cypress/e2e/customer/account/create_cards.cy.js
  cypress/e2e/customer/account/limit_change.cy.js
  cypress/e2e/customer/login_logout.cy.js
  cypress/support/customer/commands.js
  package-lock.json
  package.json
  src/components/common/AccountDetailsModal.jsx
Labels: size/L, lgtm, approved

#197 apply_loan e2e test
  cypress/e2e/customer/account/apply_loan.cy.js
  cypress/support/customer/commands.js
Labels: lgtm, size/M, approved

#198 Dosta stvari
  cypress/support/customer/commands.js
  src/components/common/NewCurrentAccountModal.jsx
  src/components/transactionComponents/FastPayments.jsx
  src/pages/portals/AccountsPortal.jsx
  src/pages/portals/EmployeeBankAccountsPortal.jsx
  src/pages/portals/EmployeePortal.jsx
  src/pages/portals/ReceiversPortal.jsx
Labels: lgtm, size/M, approved

#199 Update README.md
  README.md
Labels: lgtm, approved, size/XS

#200 update side bara
  src/App.js
  src/components/mainComponents/Sidebar.jsx
  src/context/AuthGuard.jsx
  src/pages/common/HomePage.jsx
  src/pages/loginPassword/Login.jsx
Labels: size/L, lgtm, approved

#203 Popravljene tabele da se refresuju, kartice prikaz blokada, transkacije prikaz
  cypress/e2e/admin/block_card.cy.js
  cypress/support/admin/commands.js
  src/components/common/ApproveLoanButton.jsx
  src/components/common/CreditCardDisplay.jsx
  src/components/common/DenyLoanButton.jsx
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
  src/components/transactionTable/TransactionDetailsModal.jsx
  src/components/transactionTable/TransactionItem.jsx
  src/components/transactionTable/TransactionList.jsx
  src/pages/portals/CustomerPortal.jsx
  src/pages/portals/EmployeeBankAccountsPortal.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/pages/portals/PendingLoansEmployeePortal.jsx
  src/pages/portals/PortfolioPage.jsx
  src/pages/transactions/TransactionsPage.jsx
  src/services/AxiosBanking.js
  src/styles/CreditCardDisplay.module.css
  src/styles/Transactions.module.css
Labels: lgtm, approved, size/XXL

#207 Kreiranje poslovne kartice sa ovlascenim licem, detalji za hartiju dopunjen, sredjen ui
  src/components/common/AuthorizedPersonModal.jsx
  src/components/common/CreateCardModal.jsx
  src/components/common/SecuritiesModal.jsx
  src/components/securititesBuyingComponents/SecuritiesTable.jsx
  src/context/CardContext.jsx
  src/pages/portals/CardsPortal.jsx
  src/pages/portals/ReceiversPortal.jsx
  src/services/AxiosBanking.js
  src/services/AxiosTrading.js
Labels: lgtm, approved, size/XL

#206 Ceka se bek da prosli do kraja fee i finalAmount kako bi se prikazali u transakcijama
  src/components/common/LoanRequestModal.jsx
  src/pages/exchange/ExchangeRateList.jsx
Labels: lgtm, size/S, approved

#205 companies portal, ceka se bek da bi se dohvatili podaci
  src/App.js
  src/pages/portals/CompaniesPortal.jsx
  src/services/AxiosBanking.js
Labels: lgtm, size/M, approved

#204 alert izmenjen u toast na stranici internal transfer
  src/components/transferComponents/InternalTransferForm.jsx
Labels: lgtm, size/S, approved

#209 popravljen bug
  src/pages/portals/EmployeeCardsPortal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#210 update za kreiranje novog customera i nove firme
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#212 dodat fee i finalAmount na listi transakcija
  src/components/lists/AccountTransactionLists.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
Labels: lgtm, approved, size/XS

#214 izmene poziva za interni prenos
  src/components/transferComponents/InternalTransferForm.jsx
  src/services/AxiosBanking.js
Labels: lgtm, size/M, approved

#213 The final conclusion of the exchange logic
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
  src/pages/exchange/CheckEquivalency.jsx
  src/pages/exchange/ExchangeRateList.jsx
  src/pages/portals/NewPaymentPortal.jsx
  src/services/AxiosBanking.js
  src/styles/NewPaymentPortal.css
Labels: size/L, lgtm, approved

#224 modifikacija koda new acc
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
  src/services/AxiosBanking.js
Labels: lgtm, size/M, approved

#220 Dodat exchange trankacije
  src/pages/transactions/TransactionsPage.jsx
Labels: lgtm, size/S, approved

#228 Odradjene sitne promene
  src/components/common/CreateCardModal.jsx
  src/components/common/LoanRequestModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
  src/components/lists/AccountTransactionLists.jsx
  src/components/transferComponents/InternalTransferForm.jsx
Labels: lgtm, size/M, approved

#229 Fixing Logout popup, Transaction on recent and AcountsPorta, Debit on…
  src/components/common/LogoutButton.jsx
  src/components/lists/AccountTransactionLists.jsx
  src/components/transactionComponents/RecentTransations.jsx
  src/services/transactionService.js
Labels: lgtm, approved, size/XL

#230 Popravljen dizjan za Landing page,Login,Password Reset,Password set
  package-lock.json
  package.json
  src/pages/common/Landing.jsx
  src/pages/loginPassword/Login.jsx
  src/pages/loginPassword/PasswordReset.jsx
  src/pages/loginPassword/PasswordResetConfirmation.jsx
  src/pages/loginPassword/PasswordSetConfirmation.jsx
  src/styles/Login.module.css
Labels: lgtm, approved, size/XXL

#233 Fix hot reloading when running through the proxy
  .env
  Caddyfile
  package.json
Labels: lgtm, approved, size/XS

#232 Sredjen Logout i prikaz kartice
  package-lock.json
  package.json
  src/components/common/CreditCardDisplay.jsx
  src/components/common/LogoutButton.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/styles/CreditCardDisplay.module.css
Labels: lgtm, approved, size/XL

#234 Popravljena funkcionalnost dodavanja kartice
  src/components/common/AuthorizedPersonModal.jsx
  src/components/common/CreateCardModal.jsx
  src/context/CardContext.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/services/AxiosBanking.js
Labels: lgtm, size/M, approved

#236 Nove kartice sa sliderom
  src/pages/portals/CardsPortal.jsx
  src/styles/CreditCardDisplay.module.css
Labels: size/L, lgtm, approved

#237 Sprint
  src/pages/portals/EmployeePortal.jsx
  src/pages/portals/NewPaymentPortal.jsx
Labels: lgtm, size/M, approved
