Repository RAF-SI-2024/Banka-1-Frontend, pull requests merged in 2025-04, with the labels that each got.

#239 radi test za business acc. side bar namesten.
  README.md
  cypress/downloads/downloads.htm
  cypress/e2e/admin/add_business_account.cy.js
  cypress/support/admin/commands.js
  src/App.js
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
  src/components/mainComponents/Sidebar.jsx
  src/context/AuthGuard.jsx
Labels: lgtm, approved, size/XL

#240 Menjacnica popravljena
  src/pages/exchange/CheckEquivalency.jsx
  src/pages/exchange/ExchangeRateList.jsx
Labels: lgtm, approved, size/XL

#242 radi portal za kompanije
  src/pages/portals/CompaniesPortal.jsx
Labels: lgtm, size/M, approved

#241 dodata stranica za tax tracking
  src/components/taxTrackingComponents/TaxTrackingTable.jsx
  src/pages/portals/TaxTrackingPortal.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#243 Responsive i scaling :)
  src/pages/common/Landing.jsx
  src/pages/exchange/CheckEquivalency.jsx
  src/pages/exchange/ExchangeRateList.jsx
  src/pages/portals/CardsPortal.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/styles/CreditCardDisplay.module.css
  src/styles/Login.module.css
Labels: lgtm, approved, size/XL

#244 Dodat settlmentDate za opcije i futurese, trenutno postoji change sam…
  src/components/securititesBuyingComponents/SecuritiesTable.jsx
Labels: size/L, lgtm, approved

#245 Odradjen tax info i profit info bi trebalo da je gotov(treba back da …
  src/components/common/ProfitInfoModal.jsx
  src/components/common/TaxInfoModal.jsx
  src/pages/portals/PortfolioPage.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#246 Popravljen commission u menjacnici
  cypress/downloads/downloads.htm
  src/pages/exchange/CheckEquivalency.jsx
Labels: lgtm, approved, size/XS

#248 popravljeno dodavanje korisnika i nema duplog kreiranja naloga
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
Labels: lgtm, size/M, approved

#249 Home page
  package-lock.json
  package.json
  src/components/CustomerHomePageComponent/AccountCardSection.jsx
  src/components/CustomerHomePageComponent/AccountSliderCardComponent.jsx
  src/components/transactionComponents/FastPayments.jsx
  src/components/transactionComponents/RecentTransations.jsx
  src/pages/loginPassword/PasswordSetConfirmation.jsx
  src/pages/portals/CustomerAccountPortal.jsx
  src/pages/portals/NewPaymentPortal.jsx
  src/styles/AccountCard.css
  src/styles/App.css
Labels: lgtm, approved, size/XXL

#256 kreiranje ordera
  src/components/createOrderComponents/BuyModal.jsx
  src/components/securititesBuyingComponents/SecuritiesTable.jsx
Labels: lgtm, size/M, approved

#257 Popravljen new Customer New Company and new Account, sve ok al treba …
  src/App.js
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
Labels: lgtm, approved, size/XXL

#258 portfolio page, prikaz kupljenih hartija i izmena public counta
  package-lock.json
  src/pages/portals/PortfolioPage.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#260 Ispravljen bug pt2
  package-lock.json
  src/components/common/ProfitInfoModal.jsx
  src/pages/portals/PortfolioPage.jsx
Labels: lgtm, size/S, approved

#262 fixing newAcc
  src/components/common/NewCurrentAccountModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
Labels: lgtm, size/M, approved

#259 Sprint
  src/components/common/ChangeCardLimitModal.jsx
  src/components/common/EditModal.jsx
  src/components/common/LoanRequestModal.jsx
  src/components/common/NewForeignCurrencyAccountModal.jsx
  src/pages/portals/CustomerPortal.jsx
  src/pages/portals/EmployeeBankAccountsPortal.jsx
  src/pages/portals/NewPaymentPortal.jsx
Labels: size/L, lgtm, approved

#265 Sve sa taska uradjeno osim admin home-a
  src/components/common/AccountDetailsModal.jsx
  src/components/common/ApproveLoanButton.jsx
  src/components/common/DenyLoanButton.jsx
  src/pages/exchange/ExchangeRateList.jsx
  src/pages/portals/AccountsPortal.jsx
  src/pages/portals/EmployeePortal.jsx
  src/pages/portals/LoansPortal.jsx
  src/pages/portals/PendingLoansEmployeePortal.jsx
  src/styles/AccountCard.css
  src/styles/Transactions.module.css
Labels: lgtm, approved, size/XL

#267 Fix trading service not starting in docker container
  compose.yaml
Labels: lgtm, size/S, approved

#268 zavrsena bug fixevi vezani za tranzakciju
  src/components/transactionComponents/RecentTransations.jsx
  src/services/transactionService.js
Labels: lgtm, approved, size/XS

#270 Gotov izgled celog OTC-a, povezano na slepo, ceka se back da zavrsi r…
  src/App.js
  src/components/common/CounterOfferModal.jsx
  src/components/common/MakeOfferModal.jsx
  src/components/mainComponents/Sidebar.jsx
  src/components/securititesBuyingComponents/PublicSecuritiesTable.jsx
  src/pages/portals/ActiveOffersPage.jsx
  src/pages/portals/ContractsPage.jsx
  src/pages/portals/OtcTradingPortal.jsx
  src/services/AxiosTrading.js
Labels: lgtm, approved, size/XXL

#269 popravljen actuarial management portal i uradjen actuarial performanc…
  src/App.js
  src/components/mainComponents/Sidebar.jsx
  src/pages/portals/ActuarialManagementPortal.jsx
  src/pages/portals/ActuarialPerformancePortal.jsx
  src/services/AxiosBanking.js
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#271 popravljen traiding
  compose.yaml
Labels: lgtm, size/M, approved

#272 Info Token Pop up
  package-lock.json
  package.json
  src/App.js
  src/components/common/TokenExpiryHandler.jsx
  src/pages/common/HomePage.jsx
  src/services/AxiosUser.js
Labels: size/L, lgtm, approved

#275 Fix trading service envvars
  compose.yaml
Labels: lgtm, approved, size/XS

#273 kreiranje ordera
  src/components/createOrderComponents/BuyModal.jsx
Labels: size/L, lgtm, approved

#276 HomePage admin
  src/pages/common/HomePage.jsx
Labels: size/L, lgtm, approved

#274 Card portal sredjen i option chain za hartije dovrsen skoro
  src/components/common/CardDetailsModal.jsx
  src/components/common/CreditCardDisplay.jsx
  src/components/common/SecuritiesModal.jsx
  src/pages/portals/CardsPortal.jsx
  src/services/AxiosBanking.js
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#277 U komentaru
  src/components/common/MakeOfferModal.jsx
  src/components/mainComponents/Sidebar.jsx
  src/components/securititesBuyingComponents/PublicSecuritiesTable.jsx
  src/pages/portals/ActiveOffersPage.jsx
  src/pages/portals/ContractsPage.jsx
  src/services/AxiosTrading.js
Labels: lgtm, approved

#278 Skloni se dugme 'Executed' nakon sto se klikne
  src/pages/portals/ContractsPage.jsx
Labels: lgtm, approved, size/XS

#279 Reject offer dodata ruta
  src/pages/portals/ActiveOffersPage.jsx
  src/services/AxiosTrading.js
Labels: lgtm, size/S, approved

#283 Utf 8 u compose
  compose.yaml
Labels: lgtm, approved, size/XS

#284 Zavrsen task Admin role - ceka ce backend da se testira kreiranje korisnika i kompanije
  src/components/common/CardDetailsModal.jsx
  src/components/common/CreditCardDisplay.jsx
  src/components/common/LoanRequestModal.jsx
  src/pages/portals/CardsPortal.jsx
  src/pages/portals/CustomerPortal.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/services/AxiosUser.js
  src/styles/CreditCardDisplay.module.css
Labels: size/L, lgtm, approved

#282 Front supp service PR. Wont work without routing setup locally. Do not Merge yet!
  .env
  Caddyfile
  compose.yaml
  src/components/mainComponents/ThemeToggle.jsx
  src/services/AxiosSupport.js
Labels: size/L, lgtm, approved

#286 Izmene za fast payment - vezan za userId, dodat popup i receiver over…
  src/components/transactionComponents/FastPaymentPopup.jsx
  src/components/transactionComponents/FastPayments.jsx
  src/pages/portals/CustomerAccountPortal.jsx
  src/pages/portals/NewPaymentPortal.jsx
  src/pages/portals/RecipientOverviewPage.jsx
  src/services/AxiosBanking.js
Labels: lgtm, approved, size/XL

#285 izmene buy modala
  src/components/createOrderComponents/BuyModal.jsx
Labels: lgtm, size/S, approved

#288 Ispravke za token i za rute
  src/App.js
  src/components/common/Loader.jsx
  src/components/common/LogoutButton.jsx
  src/components/common/TokenExpiryHandler.jsx
  src/components/mainComponents/Sidebar.jsx
  src/context/AuthContext.jsx
  src/context/AuthGuard.jsx
  src/pages/common/HomePage.jsx
  src/pages/loginPassword/Login.jsx
  src/pages/portals/CustomerPortal.jsx
  src/routesConfig.js
Labels: size/L, lgtm, approved

#289 Fixed trading service docker image not starting
  compose.yaml
Labels: lgtm, approved, size/XS

#290 Zavrsen option chain, istorija Forex i Future-a i sredjen Card portal
  src/components/common/CreditCardDisplay.jsx
  src/components/common/SecuritiesModal.jsx
  src/context/CardContext.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#292 mrzi me da pisem
  src/App.js
  src/components/CustomerHomePageComponent/AccountSliderCardComponent.jsx
  src/components/common/AccountDetailsModal.jsx
  src/components/transactionComponents/RecentTransations.jsx
  src/components/transactionComponents/TransactionDetailsModal.jsx
  src/pages/portals/CardsPortal.jsx
  src/pages/portals/CustomerAccountPortal.jsx
  src/pages/portals/RecipientOverviewPage.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#291 Transakcije internal ClientSec
  src/components/transactionTable/TransactionList.jsx
  src/components/transferComponents/InternalTransferForm.jsx
  src/pages/portals/securitiesBuyingPortal/ClientSecuritiesBuyingPortal.jsx
  src/styles/Transactions.module.css
Labels: size/L, lgtm, approved

#293 ispravljeno da se execute dugme sklanja kad se execute uradi
  src/components/securititesBuyingComponents/PublicSecuritiesTable.jsx
  src/pages/portals/ActiveOffersPage.jsx
  src/pages/portals/ContractsPage.jsx
Labels: lgtm, size/S, approved

#295 tax tracking table
  src/components/taxTrackingComponents/TaxTrackingTable.jsx
  src/services/AxiosTrading.js
Labels: lgtm, approved, size/XS

#299 Ipsravljena greska sa toggle dugmetom za aktivaciju
  src/components/common/CreditCardDisplay.jsx
Labels: lgtm, approved, size/XS

#304 k8s deployment
  .prow/build.yml
  Dockerfile
Labels: lgtm, size/S, approved

#298 ispravljeni popup-ovi za fast payments i payment reveivers portal
  src/components/transactionComponents/AddFastPayment.jsx
  src/components/transactionComponents/FastPaymentPopup.jsx
  src/components/transactionComponents/FastPayments.jsx
  src/pages/portals/NewPaymentPortal.jsx
  src/pages/portals/RecipientOverviewPage.jsx
Labels: lgtm, approved, size/XL

#305 Landing i login finalno
  src/pages/common/Landing.jsx
  src/styles/Login.module.css
Labels: lgtm, size/M, approved

#303 Ispravljeno da se prikazuje Exchange Rates i Currency Converter da se…
  package-lock.json
  src/pages/exchange/CheckEquivalency.jsx
  src/services/AxiosBanking.js
Labels: size/L, lgtm, approved

#308 promenjen actuarial na agent managment sad se samo ispisuju agenti, n…
  src/App.js
  src/components/mainComponents/Sidebar.jsx
  src/pages/common/HomePage.jsx
  src/pages/portals/AgentManagementPortal.jsx
  src/services/AxiosTrading.js
Labels: lgtm, size/M, approved

#309 Fixed e2e cypress
  cypress.config.js
  cypress/e2e/hello_world.cy.js
  cypress/support/admin/commands.js
  cypress/support/customer/commands.js
Labels: lgtm, size/S, approved

#315 ispravljen konflikt
  src/components/common/MakePublicModal.jsx
  src/pages/portals/PortfolioPage.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#316 popravljen protfolio portal, tj prikaz public hartija i uklanjanje se…
  src/components/securititesBuyingComponents/PublicSecuritiesTable.jsx
  src/pages/portals/PortfolioPage.jsx
Labels: lgtm, size/M, approved

#318 fast payment - onSave
  src/components/transactionComponents/FastPaymentPopup.jsx
  src/components/transactionComponents/FastPayments.jsx
Labels: size/L, lgtm, approved

#317 Odradjen dizajn za sve stranice sa taska ostao sidebar jos IMA PREVISE
  src/components/common/ResetUsedLimitButton.jsx
  src/components/mainComponents/Sidebar.jsx
  src/components/taxTrackingComponents/TaxTrackingTable.jsx
  src/pages/portals/PendingLoansEmployeePortal.jsx
  src/pages/portals/TaxTrackingPortal.jsx
  src/pages/portals/ViewOrderPortal.jsx
  src/pages/portals/securitiesBuyingPortal/ActuarySecuritiesBuyingPortal.jsx
  src/pages/transactions/TransactionsPage.jsx
Labels: size/L, lgtm, approved

#321 napokon popravljen prikaz ordera, sa pages, i ubacen filter statsu st…
  src/pages/portals/ViewOrderPortal.jsx
Labels: lgtm, approved

#322 Fix Caddyfile to use host.docker.internal
  Caddyfile
Labels: lgtm, size/S, approved

#324 Uradjena 6. stavka
  src/pages/portals/ContractsPage.jsx
Labels: lgtm, approved, size/XS

#323 Otc prikazivanje drugih akcija i toast za Make Offer
  src/components/common/MakeOfferModal.jsx
  src/components/securititesBuyingComponents/PublicSecuritiesTable.jsx
Labels: lgtm, size/S, approved

#326 ispravljeni modali za transfer i payment
  src/components/transferComponents/InternalTransferForm.jsx
  src/components/transferComponents/OtpModal.jsx
  src/components/transferComponents/VerificationModal.jsx
  src/pages/portals/NewPaymentPortal.jsx
Labels: lgtm, size/S, approved

#327 new payment recipient fix, recipient overview dodata paginacija, fast…
  src/components/transactionComponents/AddFastPayment.jsx
  src/components/transactionComponents/FastPaymentPopup.jsx
  src/components/transactionComponents/FastPayments.jsx
  src/pages/portals/NewPaymentPortal.jsx
  src/pages/portals/RecipientOverviewPage.jsx
Labels: lgtm, approved, size/XL

#328 Rola supervisor,popravljen price per unit u vieworder-u...
  src/components/createOrderComponents/BuyModal.jsx
  src/components/transactionTable/TransactionDetailsModal.jsx
  src/components/transactionTable/TransactionItem.jsx
  src/pages/portals/LoansPortal.jsx
  src/pages/portals/ViewOrderPortal.jsx
Labels: lgtm, approved, size/XL

#331 finalna verzija stranice portfolio
  src/components/common/MakePublicModal.jsx
  src/components/common/TaxInfoModal.jsx
  src/pages/portals/PortfolioPage.jsx
Labels: lgtm, size/S, approved

#329 promenjeni formati datuma vezano za loanove, i dodat period otplate k…
  src/components/common/LoanDetailsModal.jsx
  src/pages/portals/AllLoansEmployeePortal.jsx
  src/pages/portals/LoansPortal.jsx
Labels: lgtm, size/S, approved

#330 Filteri sredjeni za SecuritesTable i za PublicSecuritesTable
  src/components/securititesBuyingComponents/PublicSecuritiesTable.jsx
  src/components/securititesBuyingComponents/SecuritiesTable.jsx
Labels: size/L, lgtm, approved

#332 Testiran flow za prodaju i kupovanje securityja, ispravio da se prika…
  src/components/common/SellModal.jsx
  src/components/createOrderComponents/BuyModal.jsx
  src/services/AxiosTrading.js
Labels: lgtm, approved, size/XL

#334 HomePage za Agenta azuriran, prikaz profita i limita
  src/components/common/EditModal.jsx
  src/pages/common/HomePage.jsx
  src/pages/portals/PortfolioPage.jsx
Labels: size/L, lgtm, approved

#335 fast payment fix, new payment usagecount fix
  package-lock.json
  package.json
  src/components/transactionComponents/AddFastPayment.jsx
  src/components/transactionComponents/FastPaymentPopup.jsx
  src/components/transactionComponents/FastPayments.jsx
  src/pages/portals/NewPaymentPortal.jsx
  src/pages/portals/RecipientOverviewPage.jsx
  src/services/AxiosBanking.js
Labels: lgtm, approved, size/XL

#336 added toasts
  src/components/common/MakeOfferModal.jsx
  src/components/securititesBuyingComponents/PublicSecuritiesTable.jsx
  src/pages/portals/ContractsPage.jsx
Labels: lgtm, size/S, approved

#338 Ispravka valuta
  src/components/lists/AccountTransactionLists.jsx
  src/components/transactionComponents/RecentTransations.jsx
  src/pages/portals/AccountsPortal.jsx
  src/pages/portals/CustomerAccountPortal.jsx
Labels: lgtm, size/S, approved

#339 Promenjen datum kartice -datum pravljenja/datum isteka
  src/components/common/CardDetailsModal.jsx
Labels: lgtm, size/S, approved

#340 popravljen Bank Profit strana
  src/pages/portals/BankPerformancePortal.jsx
  src/services/AxiosTrading.js
Labels: lgtm, size/M, approved

#342 Ispravljana ruta za slanje zahteva na /exchange-transfer/preview i sa…
  src/services/AxiosBanking.js
Labels: lgtm, approved, size/XS

#341 Dodato prikazivanje ukupne dobiti na Actuarial portalu; prilagođeni s…
  src/components/taxTrackingComponents/TaxTrackingTable.jsx
  src/pages/portals/ActuarialPerformancePortal.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#343 prepravke sitnacica i pomeren bank profit na dmin str
  src/pages/common/HomePage.jsx
  src/pages/portals/ActuarialPerformancePortal.jsx
  src/pages/portals/BankPerformancePortal.jsx
  src/services/AxiosTrading.js
Labels: size/L, lgtm, approved

#344 prepravke sitnacica i pomeren bank profit na dmin str x2
  src/pages/portals/ActuarialPerformancePortal.jsx
  src/services/AxiosTrading.js
Labels: lgtm, size/M, approved

#345 Add deploy to k8s
  .prow/deploy.yaml
Labels: lgtm, size/M, approved

#346 bug fix za fast payment sa homepage
  src/components/transactionComponents/FastPaymentPopup.jsx
Labels: lgtm, approved, size/XS

#348 popravljen newPayment
  src/pages/portals/NewPaymentPortal.jsx
Labels: lgtm, approved, size/XS

#350 Fix various bugs
  src/components/common/NewCurrentAccountModal.jsx
  src/components/lists/AccountTransactionLists.jsx
  src/pages/portals/EmployeeCardsPortal.jsx
  src/pages/portals/LoansPortal.jsx
  src/pages/portals/PendingLoansEmployeePortal.jsx
  src/pages/portals/PortfolioPage.jsx
Labels: lgtm, size/M, approved

#351 A bit of tomfoolery
  compose.yaml
  src/components/taxTrackingComponents/TaxTrackingTable.jsx
  src/pages/portals/AccountsPortal.jsx
  src/pages/portals/CustomerAccountPortal.jsx
  src/services/AxiosBanking.js
Labels: lgtm, size/S, approved

#352 Update README.md
  README.md
Labels: lgtm, approved, size/XS

#353 Fix OTC names
  src/pages/portals/ContractsPage.jsx
Labels: lgtm, approved, size/XS
